import { NotificationDataType } from "./notification.types";

export const DATA: NotificationDataType[] = [
  {
    id: 1,
    userName: "Mark Webber",
    userDpUrl: "./assets/images/avatar-mark-webber.webp",
    content: "reacted to your recent post",
    contentImgUrl: "",
    timeStamp: "1m ago",
    extraData: {
      type: "post",
      content: "My first tournament today!",
    },
    unread: true,
  },
  {
    id: 2,
    userName: "Angela Gray",
    userDpUrl: "./assets/images/avatar-angela-gray.webp",
    content: "followed you",
    contentImgUrl: "",
    timeStamp: "5m ago",
    extraData: {
      type: "",
      content: "",
    },
    unread: true,
  },
  {
    id: 3,
    userName: "Jacob Thompson",
    userDpUrl: "./assets/images/avatar-jacob-thompson.webp",
    content: "has joined your group",
    contentImgUrl: "",
    timeStamp: "1 day ago",
    extraData: {
      type: "group",
      content: "Chess Club",
    },
    unread: true,
  },
  {
    id: 4,
    userName: "Rizky Hasanuddin",
    userDpUrl: "./assets/images/avatar-rizky-hasanuddin.webp",
    content: "sent you a private message",
    contentImgUrl: "",
    timeStamp: "5 days ago",
    extraData: {
      type: "message",
      content: "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    },
    unread: false,
  },
  {
    id: 5,
    userName: "Kimberly Smith",
    userDpUrl: "./assets/images/avatar-kimberly-smith.webp",
    content: "commented on your picture",
    contentImgUrl: "./assets/images/image-chess.webp",
    timeStamp: "1 week ago",
    extraData: {
      type: "",
      content: "",
    },
    unread: false,
  },
  {
    id: 6,
    userName: "Nathan Peterson",
    userDpUrl: "./assets/images/avatar-nathan-peterson.webp",
    content: "reacted to your recent post",
    contentImgUrl: "",
    timeStamp: "2 weeks ago",
    extraData: {
      type: "post",
      content: "5 end-game strategies to increase your win rate",
    },
    unread: false,
  },
  {
    id: 7,
    userName: "Anna Kim",
    userDpUrl: "./assets/images/avatar-anna-kim.webp",
    content: "left the group",
    contentImgUrl: "",
    timeStamp: "2 weeks ago",
    extraData: {
      type: "group",
      content: "Chess Club",
    },
    unread: false,
  },
]